### ISSUE TITLE
Protocol description?

### ISSUE THREAD

**Issue by jkiddo** [foxsen/fairplay-server#2]
There is no protocol description to the service but from what I can read it goes like this

first byte: command (being either 0x01 or 0x02)
second byte: total length of entire packet (being either 0x12, 0xA6 or 0x4A)
rest of the bytes: the actual challenge of length 16, 164 or 72.

Could you confirm this description?

**Comment by foxsen** [comment]
Yes. It is really that simple. 
First byte: 0x1/0x2/0x3， for fp-setup phase1/fp-setup phase2/fpdecrypt; the second byte the total length of the packet(0x12,0xA6,0x4A); rest of the bytes, come from the binary data field of related ios senders(the first two directly from http requests' binary data, the key is base64 decoded from param2 before iso9; in ios9, it comes from ekey field of SETUP request, plist_get_data_val will get it).
