### ISSUE TITLE
can't use airplay_decrypt() in fairplay.c to decrypt payload from iOS9 data port

### ISSUE THREAD

**Issue by jona1943** [foxsen/fairplay-server#4]
Use fairplay_query() to pass iOS9 airplay negotiations and get the AES key by passing ekey field of SETUP request to fairplay_query(). We can recevied airplay photo data from data port (128 bytes header + payload), but cannot use airplay_decrypt() to decrypt payload.

Any help would be appreciated!

**Comment by foxsen** [comment]
ios9的改变主要有如下这些：

1，增加了pairing的处理，这个可以用把feature最高位(bit31)不设置来避免去处理pairing
2，其他协议变化。对mirroring的流的处理和之前有些不同了，以前音频和视频两个不同端口处理协议，现在是同一个，通过plist的一些元素来区分。
3，对解码key的使用。和之前一样得到的key还需要进一步处理再作为解码密钥，见airplay.py里252行开始的部分。即把原先得到的key在与bplist得到的StreamConnectionID做一个sh512的hash，取前面16字节用
C代码大概这样：

unsigned char md[SHA512_DIGEST_LENGTH];

sprintf(tmpbuf, "%s%llu", "AirPlayStreamKey", streamConnectionID);
SHA512_Update(&ctx, tmpbuf, strlen(tmpbuf));

SHA512_Update(&ctx, key, 16);
SHA512_Final(md, &ctx);

unsigned char *buf = malloc(16);
memcpy(buf, md, 16);
AES_set_decrypt_key(buf, 128, &d->key);
bzero(md, SHA512_DIGEST_LENGTH);
sprintf(tmpbuf, "%s%llu", "AirPlayStreamIV", streamConnectionID);
SHA512_Update(&ctx, key, 16);
SHA512_Final(md, &ctx);
memcpy(d->iv
