### ISSUE TITLE
airplay_load_hwinfo, airplay_initialize_sap

### ISSUE THREAD

**Issue by yifeichingtian** [foxsen/fairplay-server#5]
I don't know these two funcitons how to realise， foxsen.lemote.com can't open。could you send the code to me？ thanks mafengmalei@163.com

**Comment by foxsen** [comment]
I have uploaded the rest parts for this project, including the source code of the two functions metioned. But that is far from complete. Read the new README to get more information

**Comment by yifeichingtian** [comment]
thank u very much!
I work on the mac os system,the .o file can't linked ,could you send me the the dylib file or .a file ?
